"""initial_schema

Revision ID: 04c0bdd2aa15
Revises: 
Create Date: 2025-11-12 23:41:26.334113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04c0bdd2aa15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_name', sa.String(), nullable=True),
    sa.Column('setting_value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_settings_id'), 'global_settings', ['id'], unique=False)
    op.create_index(op.f('ix_global_settings_setting_name'), 'global_settings', ['setting_name'], unique=True)
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False, server_default='trader'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange_name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queued_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('long', 'short', name='signal_side_enum'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('signal_payload', sa.JSON(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('replacement_count', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('is_pyramid_continuation', sa.Boolean(), nullable=True),
    sa.Column('current_loss_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.Enum('queued', 'promoted', 'cancelled', name='queue_status_enum'), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange_config_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('long', 'short', name='position_side_enum'), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'live', 'partially_filled', 'active', 'closing', 'closed', 'failed', name='group_status_enum'), nullable=False),
    sa.Column('pyramid_count', sa.Integer(), nullable=True),
    sa.Column('max_pyramids', sa.Integer(), nullable=True),
    sa.Column('replacement_count', sa.Integer(), nullable=True),
    sa.Column('total_dca_legs', sa.Integer(), nullable=False),
    sa.Column('filled_dca_legs', sa.Integer(), nullable=True),
    sa.Column('base_entry_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('weighted_avg_entry', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('total_invested_usd', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('total_filled_quantity', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('unrealized_pnl_usd', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('unrealized_pnl_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('realized_pnl_usd', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('tp_mode', sa.Enum('per_leg', 'aggregate', 'hybrid', name='tp_mode_enum'), nullable=False),
    sa.Column('tp_aggregate_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('risk_timer_start', sa.DateTime(), nullable=True),
    sa.Column('risk_timer_expires', sa.DateTime(), nullable=True),
    sa.Column('risk_eligible', sa.Boolean(), nullable=True),
    sa.Column('risk_blocked', sa.Boolean(), nullable=True),
    sa.Column('risk_skip_once', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_config_id'], ['exchange_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pyramids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('pyramid_index', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'submitted', 'filled', 'cancelled', 'failed', name='pyramid_status_enum'), nullable=False),
    sa.Column('dca_config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['position_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('offset_loss', 'manual_block', 'manual_skip', name='risk_action_type_enum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('loser_group_id', sa.UUID(), nullable=True),
    sa.Column('loser_pnl_usd', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('winner_details', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['position_groups.id'], ),
    sa.ForeignKeyConstraint(['loser_group_id'], ['position_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dca_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('pyramid_id', sa.UUID(), nullable=False),
    sa.Column('exchange_order_id', sa.String(), nullable=True),
    sa.Column('leg_index', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='order_side_enum'), nullable=False),
    sa.Column('order_type', sa.Enum('limit', 'market', name='order_type_enum'), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('gap_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('weight_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('tp_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('tp_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('status', sa.Enum('pending', 'open', 'partially_filled', 'filled', 'cancelled', 'failed', name='order_status_enum'), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('avg_fill_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('tp_hit', sa.Boolean(), nullable=True),
    sa.Column('tp_order_id', sa.String(), nullable=True),
    sa.Column('tp_executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['position_groups.id'], ),
    sa.ForeignKeyConstraint(['pyramid_id'], ['pyramids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dca_orders')
    op.drop_table('risk_actions')
    op.drop_table('pyramids')
    op.drop_table('position_groups')
    op.drop_table('queued_signals')
    op.drop_table('exchange_configs')
    op.drop_table('api_keys')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_global_settings_setting_name'), table_name='global_settings')
    op.drop_index(op.f('ix_global_settings_id'), table_name='global_settings')
    op.drop_table('global_settings')
    op.drop_table('error_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
