"""Link PositionGroup to ExchangeConfig

Revision ID: 0d52a8253769
Revises: 290c451e2875
Create Date: 2025-11-10 23:01:32.408726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d52a8253769'
down_revision: Union[str, Sequence[str], None] = '290c451e2875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_groups', sa.Column('exchange_config_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('position_groups_api_key_id_fkey'), 'position_groups', type_='foreignkey')
    op.create_foreign_key(None, 'position_groups', 'exchange_configs', ['exchange_config_id'], ['id'])
    op.drop_column('position_groups', 'api_key_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_groups', sa.Column('api_key_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'position_groups', type_='foreignkey')
    op.create_foreign_key(op.f('position_groups_api_key_id_fkey'), 'position_groups', 'api_keys', ['api_key_id'], ['id'])
    op.drop_column('position_groups', 'exchange_config_id')
    # ### end Alembic commands ###
