"""Create risk_analysis table

Revision ID: 8d64f9cea748
Revises: f4eefdcf7ef7
Create Date: 2025-11-11 13:55:07.255982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d64f9cea748'
down_revision: Union[str, Sequence[str], None] = 'f4eefdcf7ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
