"""Add LIVE to group_status_enum

Revision ID: a1b2c3d4e5f6
Revises: 83316b6b35f4
Create Date: 2025-11-15 11:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '83316b6b35f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE group_status_enum ADD VALUE 'LIVE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removing enum values is complex and not directly supported by ALTER TYPE DROP VALUE
    # without recreating the type. For a downgrade, we'll leave 'LIVE' in the enum.
    pass
    # ### end Alembic commands ###
