"""add_dca_leg_model

Revision ID: adb0cec7f79a
Revises: cce9b194cebb
Create Date: 2025-11-10 16:39:01.696222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb0cec7f79a'
down_revision: Union[str, Sequence[str], None] = 'cce9b194cebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dca_legs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dca_order_id', sa.UUID(), nullable=False),
    sa.Column('leg_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'filled', 'cancelled', 'failed', name='dca_leg_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dca_order_id'], ['dca_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dca_legs')
    # ### end Alembic commands ###
