"""Add trading models

Revision ID: c6f72a8f3b3c
Revises: e9d21b333bf2
Create Date: 2025-11-10 02:05:40.177235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6f72a8f3b3c'
down_revision: Union[str, Sequence[str], None] = 'e9d21b333bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dca_legs')
    op.drop_table('pyramids')
    op.drop_table('position_groups')
    op.create_table('position_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'live', 'partially_filled', 'closing', 'closed', name='position_group_status'), nullable=False),
    sa.Column('entry_signal', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dca_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position_group_id', sa.UUID(), nullable=False),
    sa.Column('pyramid_level', sa.Integer(), nullable=False),
    sa.Column('dca_level', sa.Integer(), nullable=False),
    sa.Column('expected_price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('filled_price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('filled_quantity', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.Enum('pending', 'filled', 'cancelled', 'failed', name='dca_order_status'), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['position_group_id'], ['position_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_groups', sa.Column('last_pyramid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('position_groups', sa.Column('unrealized_pnl_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('position_groups', sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('position_groups', sa.Column('pair', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('position_groups', sa.Column('tp_mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('position_groups', sa.Column('avg_entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('position_groups', sa.Column('unrealized_pnl_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('position_groups', sa.Column('api_key_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('position_groups_api_key_id_fkey'), 'position_groups', 'api_keys', ['api_key_id'], ['id'])
    op.create_index(op.f('ix_position_groups_user_id'), 'position_groups', ['user_id'], unique=False)
    op.create_index(op.f('ix_position_groups_pair'), 'position_groups', ['pair'], unique=False)
    op.create_index(op.f('ix_position_groups_id'), 'position_groups', ['id'], unique=False)
    op.alter_column('position_groups', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('position_groups', 'status',
               existing_type=sa.Enum('waiting', 'live', 'partially_filled', 'closing', 'closed', name='position_group_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('position_groups', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('position_groups', 'updated_at')
    op.drop_column('position_groups', 'entry_signal')
    op.drop_column('position_groups', 'symbol')
    op.drop_column('position_groups', 'exchange')
    op.create_table('pyramids',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pyramids_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('position_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['position_group_id'], ['position_groups.id'], name='pyramids_position_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pyramids_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_pyramids_id'), 'pyramids', ['id'], unique=False)
    op.create_table('dca_legs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pyramid_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_gap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('capital_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tp_target', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fill_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pyramid_id'], ['pyramids.id'], name=op.f('dca_legs_pyramid_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dca_legs_pkey'))
    )
    op.create_index(op.f('ix_dca_legs_id'), 'dca_legs', ['id'], unique=False)
    op.drop_table('dca_orders')
    # ### end Alembic commands ###
