"""Add user and user session models

Revision ID: de1944c9993e
Revises: 5a9a8da82150
Create Date: 2025-11-10 01:52:25.050194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de1944c9993e'
down_revision: Union[str, Sequence[str], None] = '5a9a8da82150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('viewer', 'trader', 'manager', 'admin', name='user_role')
    user_role_enum.create(op.get_bind())

    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # Truncate tables with foreign keys to users.id
    op.execute('TRUNCATE TABLE users, api_keys, position_groups, queued_signals RESTART IDENTITY CASCADE')

    # Drop foreign key constraints
    op.drop_constraint('api_keys_user_id_fkey', 'api_keys', type_='foreignkey')
    op.drop_constraint('position_groups_user_id_fkey', 'position_groups', type_='foreignkey')
    op.drop_constraint('queued_signals_user_id_fkey', 'queued_signals', type_='foreignkey')

    # Alter users.id
    op.alter_column('users', 'id', existing_type=sa.INTEGER(), server_default=None)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(as_uuid=True),
               existing_nullable=False,
               postgresql_using='uuid_generate_v4()')
    op.alter_column('users', 'id', server_default=sa.text('uuid_generate_v4()'), existing_type=sa.UUID(as_uuid=True))

    # Alter user_id columns in other tables
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(as_uuid=True),
               postgresql_using='uuid_generate_v4()')
    op.alter_column('position_groups', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(as_uuid=True),
               postgresql_using='uuid_generate_v4()')
    op.alter_column('queued_signals', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(as_uuid=True),
               postgresql_using='uuid_generate_v4()')

    # Recreate foreign key constraints
    op.create_foreign_key('api_keys_user_id_fkey', 'api_keys', 'users', ['user_id'], ['id'])
    op.create_foreign_key('position_groups_user_id_fkey', 'position_groups', 'users', ['user_id'], ['id'])
    op.create_foreign_key('queued_signals_user_id_fkey', 'queued_signals', 'users', ['user_id'], ['id'])

    op.create_table('user_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('role', sa.Enum('viewer', 'trader', 'manager', 'admin', name='user_role'), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_table('user_sessions')
    user_role_enum = sa.Enum('viewer', 'trader', 'manager', 'admin', name='user_role')
    user_role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
