"""Add unrealized_pnl_percent and unrealized_pnl_usd to PositionGroup

Revision ID: f4eefdcf7ef7
Revises: b0784539229e
Create Date: 2025-11-11 13:42:25.324262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4eefdcf7ef7'
down_revision: Union[str, Sequence[str], None] = 'b0784539229e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('original_signal', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_score', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('replacement_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dca_legs')
    op.add_column('dca_orders', sa.Column('price_gap_percent', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('dca_orders', sa.Column('capital_weight_percent', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('dca_orders', sa.Column('take_profit_percent', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('position_groups', sa.Column('unrealized_pnl_percent', sa.DECIMAL(precision=10, scale=4), nullable=True))
    op.add_column('position_groups', sa.Column('unrealized_pnl_usd', sa.DECIMAL(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position_groups', 'unrealized_pnl_usd')
    op.drop_column('position_groups', 'unrealized_pnl_percent')
    op.drop_column('dca_orders', 'take_profit_percent')
    op.drop_column('dca_orders', 'capital_weight_percent')
    op.drop_column('dca_orders', 'price_gap_percent')
    op.create_table('dca_legs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('dca_order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('leg_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'filled', 'cancelled', 'failed', name='dca_leg_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dca_order_id'], ['dca_orders.id'], name=op.f('dca_legs_dca_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dca_legs_pkey'))
    )
    op.drop_table('queue_entries')
    # ### end Alembic commands ###
